### ISSUE TITLE
Question: How do you use the "Reflective property animation " inspection?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#12]
v0.19

I've noticed an inspection of code similar to this (made it simple and shorter here) :

```
ObjectAnimator.ofInt(horizontalScrollView, "scrollX",123) 
```

And after using the inspection quick-fix, I got this weird code that can't be built:

```
ObjectAnimator.ofInt(horizontalScrollView, View.null, 123)
```

What is this "View.null" ? What is it supposed to be? How is it better?

**Comment by Miha-x64** [comment]
Thanks for noting. Obviously, this is a bug.

**Comment by AndroidDeveloperLB** [comment]
Oh ok.
For a moment I thought you wrote "Thanks for nothing" and was very confused...
I was about to ask why you wrote it.
:)

**Comment by AndroidDeveloperLB** [comment]
Fixed?

**Comment by Miha-x64** [comment]
![image](https://user-images.githubusercontent.com/14016119/148608539-8460c37d-5fb1-4e95-9260-8442e1bcf504.png)
Of course, as usual.

**Comment by AndroidDeveloperLB** [comment]
Oh thank you!
