### ISSUE TITLE
Request: add inspection of strings, to warn about possible duplicates

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#15]
For example if we have :

```
    <string name="choose_a_card">Choose a Card</string>
    <string name="choose_card">Choose a Card</string>
```

This also includes checking with modules, meaning that if in one module that the app uses there is the same string that is defined in the app's module (or on another module that the app is using).

This can help with translation services, to reduce the need to re-translate already translated strings.

It can also help with cases that in one module there is translation of some language to this string, and on another there isn't (or worse: it's different or a bad one, such as bad/missing placeholder).

**Comment by Miha-x64** [comment]
Android | Lint | Performance | Application Size | Duplicate Strings

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Interesting!
Does it work well?
How come it's not enabled by default? Can be very slow?

**Comment by Miha-x64** [comment]
IDK why this is disabled by default. Works pretty well for me.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I see. Worth checking out next time. Thank you!
