### ISSUE TITLE
Request: offer to merge margins/padding when possible, into horizontal/vertical/all

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#16]
Meaning in layout XML file, if there is `android:layout_marginLeft="20dp" android:layout_marginRight="20dp"` , offer `android:layout_marginHorizontal="20dp"`.

Same goes for `android:layout_marginStart="20dp"  android:layout_marginEnd="20dp"` to offer `android:layout_marginHorizontal="20dp"`.

And of course for vertical ones, from `android:layout_marginTop="20dp" android:layout_marginBottom="20dp"` into `android:layout_marginVertical="20dp"` .

And the very rare case of all sides that are the same, from `android:layout_marginLeft="20dp" android:layout_marginRight="20dp" android:layout_marginTop="20dp" android:layout_marginBottom="20dp"` into just `android:layout_margin="20dp"` . And the same if used with start&end.

Of course, if there is a mix that contradicts the merging, don't offer it. For example `android:layout_marginLeft="20dp"  android:layout_marginStart="15dp"` . However, if there is a mix that is identical (start&end&left&right with the same value, for example), offer to merge.

Same goes for padding.

If the mix is weird, I suggest to warn about it, as a different inspection.

**Comment by Miha-x64** [comment]
Yep, nice idea!
The problem is that these new horizontal/vertical attributes work in some strange way: with minSdk 21, you will end up having two layout files from one XML, default and v22, and default one would not contain these indents at all. Surprisingly, this works on SDK 21. So I need some more research to figure out for which minSdk this should be offered.

**Comment by AndroidDeveloperLB** [comment]
As I was told somewhere, this is possible on old versions of Android thanks to android-x.
So if you want to be on the safe side, offer it only for minSdk that's large enough

**Comment by Miha-x64** [comment]
Not really, this is AAPT's job: https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2/readme.md#version-2_16

The safest way is to go with minSdk 26 but who will use it?..

**Comment by Miha-x64** [comment]
I think we should go with minSdk 22.

![image](https://user-images.githubusercontent.com/14016119/153420894-5ad1d79f-62ce-4342-9366-c36f96864048.png)


![image](https://user-images.githubusercontent.com/14016119/153420804-8e906493-6396-43ef-8518-f7176181e74d.png)

**Comment by Miha-x64** [comment]
Agree.
Can I ask you to do a little research? I know that `padding` overrides `padding(Left|Top|Right|Bottom)`, and same applies for margin. What about `Start|End`, and `Horizontal|Vertical`? Can you build a list of priorities, please?

**Comment by Miha-x64** [comment]
The question is _how_ to warn. For example, I could grey out an attribute and say “paddingLeft is overridden by padding”

**Comment by AndroidDeveloperLB** [comment]
What's done? Everything? Padding, margins...?
What did you do about the weird cases?

**Comment by Miha-x64** [comment]
Reporting on attributes which could or will be overridden by others.

**Comment by AndroidDeveloperLB** [comment]
I don't understand.

**Comment by Miha-x64** [comment]
Oh, I've forgot about merging 😟

**Comment by AndroidDeveloperLB** [comment]
Merging was the original idea. The mixed cases are a special case of it...

**Comment by AndroidDeveloperLB** [comment]
Was it now added?

**Comment by Miha-x64** [comment]
![image](https://user-images.githubusercontent.com/14016119/167303287-d2c8e891-0d64-4259-82d5-4727ece91f94.png)

**Comment by AndroidDeveloperLB** [comment]
Thank you!

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 For some reason I can't find this inspection. How is it called?

Here's what I see when I search "Mike":

![image](https://user-images.githubusercontent.com/5357526/175819313-b573e1d7-902d-42a3-a238-09381a058995.png)

**Comment by Miha-x64** [comment]
@AndroidDeveloperLB
Android | Useless resource element

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 It doesn't talk about padding/margins:

"Reports useless elements of XML Drawable resources, such as single-item layer-lists, insetless insets, empty shapes, and vector elements: empty paths and clip-paths, invisible paths, useless clip-paths and groups, attributes with no effect."

And, after analyzing, I don't see even one example that it offers to merge, even though there should be...

Are you sure that's correct?

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Speaking of "The path is fully overdrawn", here:
https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/29

**Comment by Miha-x64** [comment]
@AndroidDeveloperLB, I will extend inspection description to mention all its features.

> I don't see even one example that it offers to merge, even though there should be...

Please submit a separate issue with a reproducer.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 OK here:

https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/30
