### ISSUE TITLE
Possible bug about `Replace '!!' with '?: return'` : incorrect and turned on forever

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#17]
I don't know if this inspection is by this addon, but I got it recently.
If it's not, please close this and I will write it on the Android issue tracker or IntelliJ .

![image](https://user-images.githubusercontent.com/5357526/154844559-88c8553a-a3e4-484b-afc0-a88f17412038.png)

There are 2 bugs for this inspection:
1. It's always used, even when it's turned off (and it's turned off by default).
2. It doesn't make sense, and can ruin the flow of the code.

Example is right in the inspection:

```
val number: Int? = 42
fun foo() {
    val a = number!! // Replace '!!' with '?: return'
    println(1 + a)
}
```

If we have "!!", it means that at this point, we expect it to be non-null.
If we are wrong, we will have a crash that we should know about, and fix it.

**Comment by Miha-x64** [comment]
Here it is: https://youtrack.jetbrains.com/issue/KTIJ-15635

**Comment by AndroidDeveloperLB** [comment]
Indeed it's this one, but it doesn't mention that whether it's enabled or not, it's still being used...
You've found it faster than how long it took me to write it, probably...
:)
