### ISSUE TITLE
Request: add inspection to replace `arrayOf(0,1,2)` with `intArrayOf(0,1,2)`

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#18]
The reason: intArrayOf doesn't have boxing, meaning it's not like Integer of Java. It's int instead:
https://youtu.be/Ig-rlsmKjNE?t=1443

Also requested here:
https://youtrack.jetbrains.com/issue/KT-51452

**Comment by Miha-x64** [comment]
yea, this is even planned :)

**Comment by AndroidDeveloperLB** [comment]
Who is planning it? You, or IntelliJ team?

**Comment by Miha-x64** [comment]
Done, too.
Will check out about marking my inspections.

**Comment by AndroidDeveloperLB** [comment]
How are you doing this so quickly...

**Comment by Miha-x64** [comment]
Look at the code, this was easy :)
