### ISSUE TITLE
Bug: inspection of "Reflective property animation" doesn't have quick-fix anymore on v0.21

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#20]
As the title says.

I get just a warning about it. 

![image](https://user-images.githubusercontent.com/5357526/155962903-32ded3e6-c1f4-4c51-abf2-b71b747bd3df.png)

**Comment by Miha-x64** [comment]
Fixed. Thanks for reporting!

**Comment by AndroidDeveloperLB** [comment]
Did you publish a new version?

**Comment by Miha-x64** [comment]
> Did you publish a new version?

Not yet, this is a first change in an upcoming version.

> I don't think there is anything I could do about it

You can implement an according `Property` on your own.

**Comment by AndroidDeveloperLB** [comment]
If there is no Property, I prefer not to implement it and have no warning about it

**Comment by Miha-x64** [comment]
You can suppress or disable the inspection.

**Comment by AndroidDeveloperLB** [comment]
But I like this inspection, when it has a quick-fix to offer for me

**Comment by Miha-x64** [comment]
Well, you can contribute a checkbox in inspection settings to enable or disable reporting when there's no quickfix :wink:.

**Comment by AndroidDeveloperLB** [comment]
Done:
https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/23
