### ISSUE TITLE
Request: offer inspection for Kotlin, to avoid comment-block that ends with code in the same line

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#22]
Many times, when I convert some Java code that has a comment-block and then some code beneath it (on a new line), I get them both in the same line.

For example, from this:

```
/* comment*/
foo();
```

I get this in Kotlin:

```
/* comment*/ foo()
```

Can you please add an inspection to fix this? 
I'd prefer to use `//` instead BTW. 
If this could be even another inspection (unless it's JavaDocs of course), could be nice.

**Comment by AndroidDeveloperLB** [comment]
Right. That's me.

As for "can easily swap" , that's incorrect. I have to manually go over each place and do it.

**Comment by Miha-x64** [comment]
OK, “add an ability to swap all block comments with line ones” is potentially a YouTrack issue for an existing intention in IntelliJ.
