### ISSUE TITLE
Request: read colours in json files

### ISSUE THREAD

**Issue by NZPIF** [Miha-x64/Mikes_IDEA_extensions#27]
Flutter has a great theme builder that outputs json like this

```
{
  "appBarTheme": {
    "backgroundColor": "#fffdfbff",
    "foregroundColor": "#ff3f51b5",
    "shadowColor": "#ff000000",
    ```
    It would be awesome if your extension was able to add those colours to the gutter too.

ref: https://appainter.dev/#/

**Comment by Miha-x64** [comment]
Looks quite easy to implement but there's a caveat: Android supports `#AARRGGBB` notation while CSS uses `#RRGGBBAA` one. It it OK to stick with the “alpha-first” version only?

**Comment by Miha-x64** [comment]
Closed due to inactivity, feel free to reopen.
