### ISSUE TITLE
Add a wiki with inspection descriptions

### ISSUE THREAD

**Issue by BorzdeG** [Miha-x64/Mikes_IDEA_extensions#3]
To understand why this or that inspection is implemented. For example, as does [Checkstyle](https://checkstyle.org/checks.html) or [Detekt](https://arturbosch.github.io/detekt/performance.html) or [shellcheck](https://github.com/koalaman/shellcheck/wiki/Checks)

**Comment by Miha-x64** [comment]
Nobody reads wiki. [Inspection message and quickfix](https://github.com/Miha-x64/Mikes_IDEA_extensions/commit/599b9d8d246345cc8b4763b52537d47fb88fc470) — yes, inspection description — seldom.
