### ISSUE TITLE
Bug: inspection to remove/merge margins/padding doesn't seem to work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#30]
v0.24

I'm talking about this inspection:
https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/16

Example for this:

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" tools:context=".MainActivity">

    <TextView
        android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:layout_marginLeft="12dp" android:layout_marginRight="12dp"
        android:text="Hello World!" />

</FrameLayout>
```

![image](https://user-images.githubusercontent.com/5357526/175879551-3953c3d8-0b93-4d60-991d-a97835b6948b.png)

[My Application.zip](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/8989414/My.Application.zip)

**Comment by Miha-x64** [comment]
Merging suggestion appears [on minSdk 22+](https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/16#issuecomment-1034943172).
On earlier versions aapt creates two versions of the same layout which is not good.

**Comment by AndroidDeveloperLB** [comment]
What do you mean " creates two versions of the same layout " ? 
Are you talking about the desugaring ?

**Comment by Miha-x64** [comment]
Sort of.
Just click the link from my previous message and look at the screenshot.

**Comment by Miha-x64** [comment]
Not planned, but you can contribute it.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I hope it will have it

**Comment by Miha-x64** [comment]
Suggesting works with Alt+Enter/Option+Enter but without highlighting.

**Comment by AndroidDeveloperLB** [comment]
Thanks
