### ISSUE TITLE
Bug: false positive of "Nullable argument to string concatenation" inspection

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#31]
Just this simple code would trigger this, even though I don't use a null value to concatenate to a string, at all...

```
@JvmStatic
fun getString(id: Long): String {
    var value: String = "AttrId:0x" + java.lang.Long.toHexString(id)
    return value
}
```

![wLPaRfzrhb](https://user-images.githubusercontent.com/5357526/176995128-9f16ea70-288a-4571-aca3-58b01f16933e.png)

[My Application.zip](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/9032744/My.Application.zip)

Android Studio Electric Eel | 2022.1.1 Canary 6
Build #AI-221.4501.155.2211.8738788, built on June 17, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.intellij.marketplace (221.4501.163)
    com.github.beansoft.jadx.gui.idea (2021.2.1)
    com.dubreuia (2.3.0)
    String Manipulation (9.5.0)
    Show As ... (1.0.3)
    com.google.mad-scorecard (1.2)
    net.aquadc.mike.plugin (0.24)

**Comment by Miha-x64** [comment]
The inspection was removed, see #51

**Comment by AndroidDeveloperLB** [comment]
ok thanks
