### ISSUE TITLE
Request: offer styling intention of function returning value directly, making the code shorter

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#34]
Requested this here too:

https://youtrack.jetbrains.com/issue/KTIJ-22314/Request-offer-styling-intention-of-returning-value-directly-making-the-code-shorter

**Comment by Miha-x64** [comment]
> to be offered globally

@AndroidDeveloperLB, what you mean?

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I mean to offer to change to:

fun getSomeString() = "someString"

**Comment by Miha-x64** [comment]
I believe that having explicit types (especially for public declarations) is good.

**Comment by AndroidDeveloperLB** [comment]
It's a styling inspection. It's subjective if it is good or not.
The IDE already shows the type.
