### ISSUE TITLE
Request: add Android inspection to make preferences callbacks a bit shorter

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#36]
Examples:

instead of:

```
somePreference.onPreferenceChangeListener =
            Preference.OnPreferenceChangeListener { preference: Preference?, newValue: Any? ->
...
```

use:

```
somePreference.setOnPreferenceChangeListener { preference, newValue ->
...
```

Same goes for setOnPreferenceClickListener.

Not sure if it's available on Java, but could be nice to have it there too

**Comment by Miha-x64** [comment]
Alt+Enter — Remove explicit lambda parameter types

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Doesn't work in a global scale, to search globally and apply the fix globally.

**Comment by Miha-x64** [comment]
Okay, you can contribute a fix-all-em-in-the-file quickfix.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I'm flattered, but this is out of my scope, knowledge and expertise. That's why I requested it. Otherwise I would have done it myself, on a new plugin...

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I'm flattered, but this is out of my scope, knowledge and expertise. That's why I requested it. Otherwise I would have done it myself, on a new plugin...
Here, requested on the issue tracker too:
https://issuetracker.google.com/issues/244694783

**Comment by Miha-x64** [comment]
the actual problem is in J2K, cannot be fixed properly on our side

**Comment by AndroidDeveloperLB** [comment]
It's a styling inspection. Not something to fix...

**Comment by AndroidDeveloperLB** [comment]
Should I request this on IntelliJ website?

**Comment by Miha-x64** [comment]
It's not about SharedPreferences or Android, it's about lambda parameter types in J2K.
https://youtrack.jetbrains.com/

**Comment by AndroidDeveloperLB** [comment]
OK here:
https://youtrack.jetbrains.com/issue/KTIJ-26283/Request-add-an-optional-styling-inspection-to-make-lambda-parameter-being-used
