### ISSUE TITLE
Add the ability to disable a specific hint

### ISSUE THREAD

**Issue by PhilipDukhov** [Miha-x64/Mikes_IDEA_extensions#39]
After enabling this plugin I started seeing a hint on lambda arguments

<img width="378" alt="Screenshot 2022-11-17 at 17 09 29" src="https://user-images.githubusercontent.com/6103621/202418814-d83f626c-72ee-435d-9a88-8035b728c803.png">

<img width="212" alt="Screenshot 2022-11-17 at 17 16 53" src="https://user-images.githubusercontent.com/6103621/202419957-044e4970-65ec-4ba4-8f74-25916268a1b0.png">

I find it quite noisy, especially in Compose, since it is added after every block of view content, and I would like to be able to disable it - ideally using the same mechanism I use with built-in tooltips - <kbd>⌥</kbd><kbd> ⏎</kbd> and "Disable Hint".

**Comment by Miha-x64** [comment]
Funny (no). The absence of settings on newer IDE versions seems to be an IDE bug (but I'm not 146% sure to report it to JB).
Fixed.
