### ISSUE TITLE
False positive "Useless resource element" ignoring fillAlpha

### ISSUE THREAD

**Issue by PhilipDukhov** [Miha-x64/Mikes_IDEA_extensions#41]
False positive "Useless resource element" ignoring fillAlpha

Sample code to reproduce:
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="56dp"
    android:height="56dp"
    android:viewportWidth="56"
    android:viewportHeight="56">
    <path
        android:pathData="h56v56h-56v-56"
        android:fillColor="#ffffff"
        android:fillAlpha="0.16"/>
    <path
        android:pathData="h56v56h-56v-56"
        android:fillColor="#ffffff"
        android:fillAlpha="0.16"/>
</vector>
```
Second path is marked as "invisible" and suggested to be removed. But it's visible because of first path `fillAlpha` parameter, which seems to be ignored during this inspection.

<img width="299" alt="Screenshot 2022-12-06 at 10 27 25" src="https://user-images.githubusercontent.com/6103621/205805821-0c13390b-114a-4f93-af53-4e5620f952ec.png">

**Comment by Miha-x64** [comment]
Thank you, nice catch!
