### ISSUE TITLE
Bug: false positive of "Use of reflective ObjectAnimator/PropertyValuesHolder" for GradientDrawable and customized classes too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#42]
V0.27

Examples:

```
final GradientDrawable gradientDrawable = ...;
final ObjectAnimator test = ObjectAnimator.ofInt(gradientDrawable, "color", fromColor, toColor);
final ObjectAnimator test2 =
                ObjectAnimator.ofFloat(gradientDrawable, "cornerRadius", fromCornerRadius, toCornerRadius);
```

It can also occur for a customized class:

```
public class StrokeGradientDrawable {

    public int getStrokeColor() {...}

    @Keep
    public void setStrokeColor(final int strokeColor) {...}
    public void setStrokeColor(final int strokeColor) {...}
}
```

Usage:
```
final ObjectAnimator strokeColorAnimation =
                ObjectAnimator.ofInt(drawable, "strokeColor", fromStrokeColor, toStrokeColor);
```

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 What do you mean? What can I do about it? What's the best way to do it?
What's wrong with the code?

For some animations on View , I can use the `View.someFieldConstant`. What can I do here?

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I didn't know about this. 
1. It avoids reflection this way, somehow? Wouldn't it still need reflection to find this?
2. Can you please explain how to use it? 
3. Please consider adding this as quick-fix, or at least have an example like here, but on the docs when seeing such a warning.

**Comment by Miha-x64** [comment]
Okay, here's some sort of ObjectAnimator tutorial.
1. By specifying string property name, you make animator search for property by name. But there's no such thing as “property” or “name”, there are `getXxx()` and `setXxx(value)` methods looked up with JNI or reflection. By not using string name you're not forcing animator to use this trick, thus no reflection. That's why typical proguard-rules contain `-keep View { get*()/set*(*) }` rules, and you won't need them after the fix.
2. Just look at `View.someFieldConstant` and do the same thing.
3. Will add a live template `property`.
4. Yes. `GradientDrawable` colors are `ColorStateList`s, and every `setColor(new value never seen before)` call allocates a new one. A custom Drawable with simple `drawRoundRect()` implementation should perform better.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 It won't use reflection when using a property? Then how could it find the property? How does it work behind the scenes?

Maybe what you are doing puts the reference to it via a HashMap that knows about the classes and the properties, so it will have the class name and the "color" as key to reach what you've created? Meaning class+propertyName as keys, and the declaration of what you created as value?

If so, is this what the common View constants do, too?
I thought they have some switch-case for this, built-in.

About GradientDrawable, I see. I didn't think about this because I didn't create this code. I don't know if it will cause issues to try to optimize it.

Thank you!

**Comment by Miha-x64** [comment]
> Then how could it find the property?

You pass it directly. No need to search for thing which is already in your hands.

> How does it work behind the scenes?

With `String propertyName`, animator looks up get*** or set*** method with JNI or reflection. With `Property<>`, there's a property already.

> what you are doing puts the reference to it via a HashMap that knows about the classes and the properties

Nope, vice versa. If you're using property name, there's some internal cache of JNI handles. If you're passing a Property, no need to cache anything.

> is this what the common View constants do, too? I thought they have some switch-case for this, built-in.

If you Ctrl/Cmd+click a `View.PROPERTY` in the IDE, [the truth reveals](https://android.googlesource.com/platform/frameworks/base/+/a175a5b/core/java/android/view/View.java#14146).

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I can't access this link. But I now tried, and you are correct. I thought those are simple constants or something, but it's not:

```
    /**
     * A Property wrapper around the <code>rotation</code> functionality handled by the
     * {@link View#setRotation(float)} and {@link View#getRotation()} methods.
     */
    public static final Property<View, Float> ROTATION = new FloatProperty<View>("rotation") {
        @Override
        public void setValue(View object, float value) {
            object.setRotation(value);
        }

        @Override
        public Float get(View object) {
            return object.getRotation();
        }
    };
```

So for summary, you suggest using these, right:
1. For a custom View, have a property like here.
2. For the GradientDrawable, instead of "color", create a new property that will set for drawRoundRect . Also need a getter?

**Comment by Miha-x64** [comment]
1. Yes.
2. For a custom Drawable, yes, and yes.

**Comment by AndroidDeveloperLB** [comment]
Wait I missed the part that I need to change GradientDrawable to a customized version of it.
Or you meant that I could just have some static constant of the property for reaching it for all GradientDrawable ?

**Comment by Miha-x64** [comment]
We've been talking about calling `drawRoundRect()`. If not in a custom Drawable, where then?

**Comment by AndroidDeveloperLB** [comment]
I'm confused. You mean to extend GradientDrawable , then, and add a property there?
Or something else?

**Comment by Miha-x64** [comment]
Nope, just create your own Drawable.

**Comment by AndroidDeveloperLB** [comment]
ok thanks.
