### ISSUE TITLE
Request: add inspection to add ID for scrolling Views, such as NestedScrollView

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#45]
The reason:

Without an ID, such Views lose their state when onSaveInstanceState is called.

**Comment by Miha-x64** [comment]
Thanks, great idea!

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 How are you doing these things so fast?
How did you support all of them?
