### ISSUE TITLE
Request: add warning when a padding/margin seem to be used to override, but actually doesn't do anything

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#46]
If I have in a layout XML a value for "padding", and also for "paddingBottom", sadly the "paddingBottom" doesn't do anything. 

I sometimes make this mistake, because I think to myself : "I've created a general rule, and also an exception to the rule".

In this case, the proper way to fix it is to split the "padding" to "paddingHorizontal" and "paddingTop", so that "paddingBottom" would do what it's supposed to do.

I don't remember how it works for margins.

Please offer a warning about such a case and similar cases.

**Comment by Miha-x64** [comment]
wait, but we [already have this](https://github.com/Miha-x64/Mikes_IDEA_extensions/blob/master/src/main/kotlin/net/aquadc/mike/plugin/android/res/MarginsPaddings.kt#L43-L87)

**Comment by AndroidDeveloperLB** [comment]
We have? Odd. I didn't see it warn about it.
Do I have to enable it , or is it enabled by default?
How is it called? I will check if it's enabled or not.

**Comment by Miha-x64** [comment]
“Useless resource element” inspection

**Comment by AndroidDeveloperLB** [comment]
It's manual or automatic? Will just opening the layout file show the warning?

**Comment by Miha-x64** [comment]
The inspection is enabled by default and works automatically.
![Screenshot](https://plugins.jetbrains.com/files/12690/screenshot_deb0d189-19d6-4590-a57c-2f00680ef625)

It it doesn't work in your case, and Gradle is synced, then there's a bug, please post your code here.

**Comment by AndroidDeveloperLB** [comment]
Sorry for some reason the plugin wasn't installed anymore. No idea why
