### ISSUE TITLE
Request: add inspections for things that look useless in VectorDrawable (stroke, fill)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#48]
Could be weak-level inspections by default, but probably useless in most cases to have these, for example:

1. strokeWidth without strokeColor or with strokeColor that is completely transparent
2. strokeColor that is completely transparent or without strokeWidth 
3. fillAlpha without fillColor
4. fillColor  that is completely transparent 

Maybe other cases I didn't think of, because I'm not an expert at all about VectorDrawable.

The reason it might be weak-level inspection is that maybe in some cases it's intentional, when you want to animate/change things at runtime.
Sadly there isn't an official way to do it that I've found (found a request here: https://issuetracker.google.com/issues/172425450 ), but there are some old libraries that promise to do it:
https://github.com/devendroid/VectorChildFinder
https://github.com/harjot-oberai/VectorMaster

The reason I see these is conversion from SVG. Sometimes bad conversion, too.

Please let me know if I'm wrong here.

**Comment by Miha-x64** [comment]
![image](https://user-images.githubusercontent.com/14016119/228279813-4b3970e6-9fab-4d23-9fe8-e977e63a6694.png)
do you have the plug-in installed?

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Yes. It's not showing. 
See screenshots:
[screenshots.zip](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/11090936/screenshots.zip)

Perhaps the inspection is disabled? What is its name?
Perhaps I've disabled it as it was merged with one that I didn't like...

**Comment by Miha-x64** [comment]
That's the same inspection, “Useless resource element”.

**Comment by AndroidDeveloperLB** [comment]
It's turned on, and still I don't see this error/warning.

There is also this thing that seems to be useless:

```
<aapt:attr name="android:fillColor">
```

No idea what it does, but removing it doesn't seem to do anything.

Can you please share a sample project that it works fine for you? I will try to open and see...

**Comment by Miha-x64** [comment]
There's a test project inside the repo.
Here's a [vector drawable with a lot of problems](https://github.com/Miha-x64/Mikes_IDEA_extensions/blob/master/TestProject/app/src/main/res/drawable/ic_android.xml) showing up when Gradle is synced.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 OK so I tried it on a new project , with just this file inside. Made sure the "Android | Useless resource element" is enabled.
Then I went into the file, and I see no warning.
I also chose to manually analyze this file, and still nothing.

Please tell me what to do next.

See attached:

[studio64_2023-04-04_13-16-22.zip](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/11147356/studio64_2023-04-04_13-16-22.zip)

Perhaps related to Android Studio version?

Android Studio Giraffe | 2022.3.1 Canary 11

**Comment by Miha-x64** [comment]
I believe that the problem is in AS Canary version.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Sorry for that. I use Canary because stable has its own issues.
Each of them has some bugs...
I have to choose which bugs I can tolerate...
