### ISSUE TITLE
Request: add inspection of using "entries" for enum classes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#49]
We have an inspection for caching the "values", but it seems there might be a better inspection, to use "entries".

It's currently in experimental phase, but maybe you could have an inspection for it now, and mark it too as experimental and turned off by default.

Video about it:
https://youtu.be/R1JpkpPzyBU?t=340

Not sure if it's available for Android projects. 
If you try it out, please let me know and have a sample to show that it works. I hope it's possible for Android projects too.

**Comment by AndroidDeveloperLB** [comment]
Seems it should be built-in anyway:
https://kotlinlang.org/docs/whatsnew1820.html#a-modern-and-performant-replacement-of-the-enum-class-values-function

Should I close this request?

**Comment by Miha-x64** [comment]
The inspection will stop reporting `values()` in the next release.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I don't understand. What will stop reporting? Which inspection?
The request is to add one. 
Are you talking about the caching inspection of it?

**Comment by Miha-x64** [comment]
it's on Kotlin side now https://github.com/Kotlin/KEEP/pull/284/files#diff-7d80189eff26c4d9fb3721434ed13e43a9a896e3446d9a1b4447d93f3a21a599R57

**Comment by AndroidDeveloperLB** [comment]
oh ok. I thought it might indeed be
