### ISSUE TITLE
how do i use this on hedgehog canary please help

### ISSUE THREAD

**Issue by Osanosa** [Miha-x64/Mikes_IDEA_extensions#50]

**Comment by Miha-x64** [comment]
What's the problem?

**Comment by Osanosa** [comment]
I've installed extension but there's no commands in description or else i just don't know how to use it and there's no custom toolbars or else please provide a tutorial

**Comment by Osanosa** [comment]
![image](https://user-images.githubusercontent.com/80209416/234594134-b8296e22-f43e-41e1-b4b6-4bec1450f997.png)

**Comment by Miha-x64** [comment]
Probably your “hedgehog canary” (whatever that means) is incompatible with the plugin. It should report errors with stack traces, then.

**Comment by Osanosa** [comment]
Android studio latest canary is hedgehog. what do i do now?

**Comment by Miha-x64** [comment]
Try out the new version. If anything breaks–open an issue and attach a stack trace from IDE log.

**Comment by Osanosa** [comment]
I don't know how to use it 😭
Please provide instructions

**Comment by Miha-x64** [comment]
If you've installed the plugin from the marketplace, it just works. If it doesn't, see logs for stack traces.
