### ISSUE TITLE
Fix `Heavyweight property delegation` warning

### ISSUE THREAD

**Issue by jonrysimbolon** [Miha-x64/Mikes_IDEA_extensions#52]
i always add this snippet code to use datastore
`private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = BuildConfig.SETTINGS_PREF)`
but this warning always appear

> Heavyweight property delegation

how to fix it ?

**Comment by Miha-x64** [comment]
`operator` functions `getValue`, `setValue`, `provideDelegate` should be `inline`.

[Inspection description](https://github.com/Miha-x64/Mikes_IDEA_extensions/blob/master/src/main/resources/inspectionDescriptions/ktPropBy.html): “Am I a joke to you?”

**Comment by jonrysimbolon** [comment]
thank you sir
