### ISSUE TITLE
Wrong inline hint.

### ISSUE THREAD

**Issue by danny-su** [Miha-x64/Mikes_IDEA_extensions#53]
<img width="961" alt="image" src="https://github.com/Miha-x64/Mikes_IDEA_extensions/assets/12178855/bcbe09ee-86df-46b4-837d-f42d3fa462de">

**Comment by Miha-x64** [comment]
This is inspection message, not a hint.
Inline hints (`this: MutableMap<String, Any>`, `^run`) look differently.
