### ISSUE TITLE
How to improve the code to avoid "heavyweight property delegation" hint.

### ISSUE THREAD

**Issue by danny-su** [Miha-x64/Mikes_IDEA_extensions#54]
<img width="652" alt="image" src="https://github.com/Miha-x64/Mikes_IDEA_extensions/assets/12178855/3eb92cd6-f445-4b38-98bc-70e3323fe9fa">

The following is the function definition:
``` kotlin
inline fun <reified R : Any> arg(
    needLock: Boolean = false,
    noinline converter: (Any) -> R = getDefaultConverter()
) =
    PropertyDelegateProvider<ArgumentProvider, ReadOnlyProperty<ArgumentProvider, R?>> { _, _ ->
        ReadOnlyProperty { thisRef, property ->
            thisRef.getArgument(property.name, needLock, converter)
        }
    }
```

**Comment by Miha-x64** [comment]
https://github.com/Miha-x64/Mikes_IDEA_extensions/issues/52#issuecomment-1669936704

**Comment by danny-su** [comment]
@Miha-x64 Is there any chance to suppress the inspection message of "expected performance impact ..." ?
<img width="1335" alt="image" src="https://github.com/Miha-x64/Mikes_IDEA_extensions/assets/12178855/27716b36-3523-4ca4-b467-8d410fb9dea6">

**Comment by Miha-x64** [comment]
@danny-su `@Suppress("NOTHING_TO_INLINE")` (or Alt/Option+Enter → Suppress…)
