### ISSUE TITLE
Bug: when the plugin is used, some inspections of the IDE don't work anymore

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#55]
I've tested and it seems that the inspection for removal of useless "!!" is gone:
https://youtrack.jetbrains.com/issue/KTIJ-26703

When disabling the plugin, it works fine. When enabling it (and restarting the IDE), it's not showing it.
And I think some other inspections might not work, as well.

Please check it out. This is a very useful plugin...

I've tested it even on this version of the IDE:
Android Studio Iguana | 2023.2.1 Canary 1
Build #AI-232.8660.185.2321.10696284, built on August 22, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Show As ... (1.1.1)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.marketplace (232.8660.205)
    String Manipulation (9.10.0)
    GenerateSerialVersionUID (3.0.3)
    idea.plugin.protoeditor (232.8660.88)
    com.steve.plugins.autoscroll (1.1)
    com.dethlex.numberconverter (1.5.0)
    izhangzhihao.rainbow.brackets (2023.3.3)
    com.ppismerov.ksvu (0.0.1)
    net.aquadc.mike.plugin (0.29)
    com.developerphil.adbidea (1.6.11)
    GenerateSerializationHelpers (1.0.6)

**Comment by AndroidDeveloperLB** [comment]
I think I should close here, because someone created a report about this here:
https://youtrack.jetbrains.com/issue/IDEA-331145/Inspect-Problems-section-is-not-open-Code-Inspect-File-Analyze-with-enabled-Mikes-IDE-Extensions-plugin

What do you think?

**Comment by Miha-x64** [comment]
You're successful at creating a lot of issues at once but, to begin with, can you send IDE log please? I'm not very keen on installing a specific Android Studio build and trying to reproduce your setup, at least without having any clue about what happens inside.

If you don't want to share the log publicly, you can send it to https://twitter.com/miha_x64 or https://t.me/Harmonizr.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 I've contacted you on X. Please answer so that I can send you

**Comment by AndroidDeveloperLB** [comment]
Both Google and IntelliJ teams wrote information about the issue, that it comes from the plugin.
Please fix. I've tried to contact you on X, too.

**Comment by Miha-x64** [comment]
Does [this release](https://plugins.jetbrains.com/plugin/12690-mike-s-ide-extensions/versions/stable/389133) fix the issue for you?
To verify that both incompatible changes by Google are worked around, please
* open a layout with margin/padding left/top/right/bottom/start/end/horizontal/vertical mix and see inspection works
* open a vector drawable with some issues and see inspection works
if anything breaks, please post IDE stack traces here.

**Comment by AndroidDeveloperLB** [comment]
When updating the plugin, it got an exception. I don't know if reporting there can help you reach it, but here:

[log.txt](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/12533935/log.txt)

I can't open the original project for some reason, so I created a new one.
In it, the bug seems to be fixed, at least for the useless "!!" inspection.

![image](https://github.com/Miha-x64/Mikes_IDEA_extensions/assets/5357526/20ad4a80-f0e0-439f-b499-d1df7ddfa845)

[My Application.zip](https://github.com/Miha-x64/Mikes_IDEA_extensions/files/12534172/My.Application.zip)


Android Studio Iguana | 2023.2.1 Canary 2
Build #AI-232.9559.62.2321.10749089, built on September 1, 2023
Runtime version: 17.0.8+0--10699129 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Show As ... (1.1.1)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.marketplace (232.9559.64)
    String Manipulation (9.11.3)
    GenerateSerialVersionUID (3.0.3)
    idea.plugin.protoeditor (232.9559.10)
    com.steve.plugins.autoscroll (1.1)
    com.dethlex.numberconverter (1.5.0)
    izhangzhihao.rainbow.brackets (2023.3.4)
    com.ppismerov.ksvu (0.0.1)
    net.aquadc.mike.plugin (0.30)
    com.developerphil.adbidea (1.6.11)
    GenerateSerializationHelpers (1.0.6)

**Comment by Miha-x64** [comment]
Your log shows previous (0.29) version of my plugin.

**Comment by Miha-x64** [comment]
I hope we're done with this.

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Yes.
BTW, it's not 0.29. It's 0.30 there
