### ISSUE TITLE
Request: Compose colors

### ISSUE THREAD

**Issue by mtrakal** [Miha-x64/Mikes_IDEA_extensions#59]
I love your plugin, now I miss just color picker / color rectangle for compose variant of colors:
```kotlin
package presentation.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

```

It would be nice, if plugin support this hex format of color :). Hope, that's not some Koala bug (didn't try same code on Iguana / Jelly Fish version)

Android Studio Koala | 2024.1.1 Canary 3
Build #AI-241.14494.158.2411.11648550, built on March 29, 2024
Runtime version: 17.0.10+0--11609105 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 12288M
Cores: 32

**Comment by mtrakal** [comment]
Edit: it's working on Jelly Fish 🙈

![image](https://github.com/Miha-x64/Mikes_IDEA_extensions/assets/1458891/56775317-12cb-4af1-99c8-cb59a53c0ec9)

**Comment by Miha-x64** [comment]
There are constant changes both in IntelliJ and Android plugin APIs.
Please check out IDE for plugin crashes and share the stack trace.

**Comment by mtrakal** [comment]
Hmm, I don't know what's happen, but today after restart Android studio it's working on Koala without any changes 🙈.

Closing for now, when it happen again and show stacktrace, I'll reopen it.
