### ISSUE TITLE
ktNoinlineFunc appears on valid (?) code

### ISSUE THREAD

**Issue by BorzdeG** [Miha-x64/Mikes_IDEA_extensions#6]
plugin version: 0.10
IDEA version: IntelliJ IDEA 2020.1 Beta (Build #IU-201.6668.13)
Kotlin version: 1.3.70

```
import org.gradle.api.Project
import org.gradle.api.artifacts.component.ModuleComponentIdentifier

internal fun getDependencies(project: Project): List<ModuleComponentIdentifier> {
	return project.configurations.asSequence().filter {
		it.isCanBeResolved && !it.name.endsWith("Metadata")
	}.map {
		it.resolvedConfiguration.resolvedArtifacts
	}.flatten().distinct().map {
		it.id.componentIdentifier
	}.filterIsInstance(ModuleComponentIdentifier::class.java).toList()
}
```

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2332528/77915716-99ddb880-72a0-11ea-89c4-d453a70eea5e.png">

**Comment by Miha-x64** [comment]
Yep, this inspection does not say it's invalid. It warns that function is not inline so anonymous class will be declared and instantiated.
That's why it is a ‘weak warning’, and that's why it highlights only a single character. If it still annoys you, just turn it off.
