### ISSUE TITLE
Request: use "@RequiresApi" instead of "@androidx.annotation.RequiresApi" as annotation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#8]
No need to have the full path, unless there is some other "RequiresApi" of some other package name that's being used in the current file...

**Comment by AndroidDeveloperLB** [comment]
@Miha-x64 Closed because fixed?

**Comment by Miha-x64** [comment]
@AndroidDeveloperLB, yep, see the commit message :)

**Comment by AndroidDeveloperLB** [comment]
OK thanks
